### ISSUE TITLE
Number of Satellites always showing zero

### ISSUE THREAD

**Issue by hgg2k** [moschotto/Taranis_X9#1]
The lua script works fine on the Taranis X9D except the number of satellites which is always zero.
The X9D variable Sats is shown correctly on a different screen.

**Comment by moschotto** [comment]
do you get any readings from TMP2 and did you add / discover this sensor?


https://github.com/betaflight/betaflight/blob/master/docs/Telemetry.md
=> Tmp2 | number of sats. Every second, a number > 100 is sent to represent GPS signal quality.

![simulator](https://user-images.githubusercontent.com/10543292/70391466-e772a480-19d5-11ea-9059-cec1495dace3.png)

**Comment by hgg2k** [comment]
I do not have any Tmp2 sensor value.
I have **Sats** which correctly displays the number of satellites.

![Sats](https://user-images.githubusercontent.com/5998571/70391715-e2ffb900-19e0-11ea-9050-84adb07de430.jpg)

Even when I rescan for new sensors.  Sats only.
(What about if I rename the Sats sensor value to Tmp2?)

**Comment by moschotto** [comment]
if it's comming via "Sats" just rename the variable:

gpssatId = getTelemetryId("Tmp2")
=> gpssatId = getTelemetryId("Sats")

**Comment by hgg2k** [comment]
Yep, it worked!
Thanks.
