### ISSUE TITLE
store coordinates to file

### ISSUE THREAD

**Issue by m4R-T1n** [moschotto/Taranis_X9#2]
this is a great simple script. i have tried it on my X9D+ 2019 and i love it.
can you please add a function to store the last 4 coordinates in a txt file?
so if you lost the aircraft you can turn off the transmitter and can look at the txt file for the last 4 coordinates to search for it (last 4 so you can get the direction the aircraft was flying)
or if its possible to add a screenshot when pressing or longpressing a button.
thank you

**Comment by moschotto** [comment]
did you check the description?

Description:

stores GPS coordinates every second into **/SCRIPTS/TELEMETRY/GPSpositions.txt** and displays the last 4 GPS positions and GPS sattelite count on the telemetry screen. In case that telemetry is not available anymore (crash, power loss etc.) the screen won't be updated but still shows the last 4 postions. If 50 postions are stored, the log will be reset and starts at 0.



it's very unlikely that you don't have anything in the log. Please double check...

**Comment by m4R-T1n** [comment]
second try was working and stored the data, thank you
